# Generated by Django 3.2.24 on 2024-05-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_rename_author_post_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='community.Subject'),
        ),
    ]
