# Generated by Django 3.2.24 on 2024-05-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('community', '0005_alter_post_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='profiles.userprofile'),
        ),
    ]
