# Generated by Django 3.2.24 on 2024-05-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderlineitem_product_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
