# Generated by Django 3.2.24 on 2024-05-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Archived')], default=0),
        ),
    ]
