# Generated by Django 3.2.24 on 2024-05-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_subscription',
            new_name='has_expiration_date',
        ),
    ]
